### ISSUE TITLE
:Mru without FileFinder() throws error message

### ISSUE THREAD

**Issue by Konfekt** [mg979/vim-mini-plugins#2]
Calling `:Mru`, without `FileFinder()`, produces  the error message

```vim
Errore/i eseguendo function <SNR>165_mru_fzf[23]..fzf#vim#files[15]..<SNR>414_fzf[
21]..fzf#run:
riga   75:
E488: Caratteri in più a fine comando
Errore/i eseguendo function <SNR>165_mru_fzf:
riga   23:
E171: Manca :endif
```

**Comment by Konfekt** [comment]
I close this issue for the  time being as it only appears if `.zshrc` is not loaded and also with another fzf plug-in.

**Comment by Konfekt** [comment]
Indeed, the reason of the issue was that `$FZF_DEFAULT_COMMAND` was only set in `.zshrc` and not in `.zshenv`.

**Comment by Konfekt** [comment]
As I am new to FZF, @mg979, could you hint at where is `FileFinder()` defined?

**Comment by mg979** [comment]
`FileFinder()` is no

**Comment by mg979** [comment]
Fixed in https://github.com/mg979/vim-mini-plugins/commit/3824c25b69a68df30dfedcf51ef2cdaa3ee60c1f

**Comment by Konfekt** [comment]
To understand what `:Mru` tries to achieve: where is `FileFinder()` from?

**Comment by mg979** [comment]
It's a function I'm using where I don't have fzf, it's not in a plugin. Before it was checking for `g:loaded_finder` (where I have this function), for some reason you had this variable set, so it was looking for a function that wasn't there.
