### ISSUE TITLE
Allow custom highlight group in marksigns

### ISSUE THREAD

**Issue by savchenko** [mg979/vim-mini-plugins#3]
Currently, bright red is hard-coded:
```vim
fun! s:higroup() abort
  " Create/restore highlight group for signs. {{{1
  let gui  = has('gui_running') || (has('termguicolors') && &termguicolors)
  let mode = gui ? 'gui' : 'cterm'
  let hi   = synIDattr(synIDtrans(hlID('SignColumn')), 'bg', mode)
  let color = empty(hi) || hi == -1 ? mode.'bg=NONE' : mode.'bg='.hi
  exe 'silent! hi! MarkBar guifg=Red ctermfg=9' color
endfun "}}}
```
Perhaps allow user to change this or query GitGutter's "deleted" group?

**Comment by mg979** [comment]
I think bright red works well for all colorschemes, both dark and light. What problem do you have with it? Linking it to GitGutter `deleted` group would make it stand out less, I don't see it as an improvement.

**Comment by savchenko** [comment]
OK, how about setting to the very same bright red, but declared as hex rather then `Red`? This way user can target `MarkBar` in their theme.

**Comment by mg979** [comment]
I think you can relink the group anyway, with

    hi! link MarkBar SomeGroup

I should use `default` in the group definition.

**Comment by mg979** [comment]
> but declared as hex rather then Red

Ok I can do that.

**Comment by savchenko** [comment]
> I think you can relink the group anyway, with

Interestingly, I see the `Red` taking precedence. It works if I change it to a hex colour in `marksigns.vim` .

> I should use default in the group definition.

This or hex trick should do.

**Comment by savchenko** [comment]
> Linking it to GitGutter deleted group would make it stand out less, I don't see it as an improvement.

You are correct there. After some local tinkering what does make sense is to separate marks from GitGutter signs.

If the default git-signs are red/yellow/green (delete/change/add), then making `MarkBar` blue will yield the highest visual contrast. 

Obviously, it is all theme-dependant.

**Comment by mg979** [comment]
Can you try now? I'm using both `default` and the hex code.

**Comment by savchenko** [comment]
> Can you try now? I'm using both `default` and the hex code.

Works just fine. Thanks.
